with open("src/arena/test_procedural_arena.py", "r") as f:
    content = f.read()

old = """        assert hazard.kind in ["spikes", "lava", "fake_booster", "decoy_item", "breakable_wall", "link_booster", "stamina_booster", "silence_booster", "poison_cloud", "proximity_trap", "explosive_barrel", "healing_spring", "trap", "spinning_laser", "laser_wall", "meteor", "conveyor_belt", "gravity_well", "reverse_gravity", "black_hole", "portal", "teleporter", "one_way_teleporter", "swap_portal", "placeable_trap_item", "portal_gun_item", "flare", "crater", "bumper", "tornado", "lightning_storm", "hidden_trap", "lightning_strike", "switch", "magnet", "temporal_rift", "fire_zone", "quicksand", "sinkhole", "damage_link", "weather_booster", "magnet_booster", "fire_ring", "wormhole", "clone_booster", "stealth_zone", "invert_booster"]"""
new = """        assert hazard.kind in ["spikes", "lava", "fake_booster", "decoy_item", "breakable_wall", "link_booster", "stamina_booster", "silence_booster", "poison_cloud", "proximity_trap", "explosive_barrel", "healing_spring", "trap", "spinning_laser", "laser_wall", "meteor", "conveyor_belt", "gravity_well", "reverse_gravity", "black_hole", "portal", "teleporter", "one_way_teleporter", "swap_portal", "placeable_trap_item", "portal_gun_item", "flare", "crater", "bumper", "tornado", "lightning_storm", "hidden_trap", "lightning_strike", "switch", "magnet", "temporal_rift", "fire_zone", "quicksand", "sinkhole", "damage_link", "weather_booster", "magnet_booster", "fire_ring", "wormhole", "clone_booster", "stealth_zone", "invert_booster", "shrinking_zone"]"""
content = content.replace(old, new)

old2 = """        assert hazard.damage > 0 or hazard.kind in ["healing_spring", "placeable_trap_item", "portal_gun_item", "decoy_item", "breakable_wall", "portal", "teleporter", "one_way_teleporter", "swap_portal", "flare", "crater", "bumper", "temporal_rift", "link_booster", "stamina_booster", "silence_booster", "drone_item", "stealth_drone_item", "shadow_booster", "switch", "magnet", "temporal_rift", "quicksand", "sinkhole", "damage_link", "weather_booster", "magnet_booster", "fire_ring", "wormhole", "clone_booster", "stealth_zone", "invert_booster"]"""
new2 = """        assert hazard.damage > 0 or hazard.kind in ["healing_spring", "placeable_trap_item", "portal_gun_item", "decoy_item", "breakable_wall", "portal", "teleporter", "one_way_teleporter", "swap_portal", "flare", "crater", "bumper", "temporal_rift", "link_booster", "stamina_booster", "silence_booster", "drone_item", "stealth_drone_item", "shadow_booster", "switch", "magnet", "temporal_rift", "quicksand", "sinkhole", "damage_link", "weather_booster", "magnet_booster", "fire_ring", "wormhole", "clone_booster", "stealth_zone", "invert_booster", "shrinking_zone"]"""
content = content.replace(old2, new2)

with open("src/arena/test_procedural_arena.py", "w") as f:
    f.write(content)
