import pytest
from arena.arena_types import ThunderstormArena

def test_thunderstorm_arena_spawns_lightning():
    arena = ThunderstormArena()
    arena.generate()

    # We don't care about the initial hazards generated by ProceduralArena,
    # we just want to know if calling update_zone past the interval adds a new one.

    # Run the timer up to right before interval
    arena.update_zone(current_tick=1, delta=1.9)
    # the base class might add hazards during update_zone occasionally, so let's check specifically for lightning

    lightning_hazards = len([h for h in arena.hazards if getattr(h, "kind", "") == "lightning"])

    # Tick past interval
    arena.update_zone(current_tick=2, delta=0.2)

    # Initially it spawns a warning
    warnings = [h for h in arena.hazards if getattr(h, "kind", "") == "lightning_warning"]
    assert len(warnings) > 0
    assert warnings[-1].damage == 0.0
    assert getattr(warnings[-1], "duration", None) > 0

    # Tick past the warning duration
    arena.update_zone(current_tick=3, delta=1.5)

    # Verify the new hazard is lightning
    lightning = [h for h in arena.hazards if getattr(h, "kind", "") == "lightning"]
    assert len(lightning) > lightning_hazards
    assert lightning[-1].damage == 300.0
    assert getattr(lightning[-1], "duration", None) > 0
